on:
  schedule:
    - cron: '10 16 * * *'
  workflow_dispatch:
    inputs:
      push_files:
        description: 'Restart at the file push step'
        required: true
        default: 'false'

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run automation script
      run: python automation_script.py

    - name: Push updated data to GitHub
      if: ${{ inputs.push_files == 'true' }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated data update"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
